name: Build and Deploy

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v1
        with: 
          node-version: 16
          cache: 'npm'

      - name: Install Gatsby CLI
        run: npm install --location=global gatsby-cli

      - name: Install Dependencies
        run: npm install

      - name: Build the Gatsby Cli
        run: gatsby build
      
      - name: Verify the Public Folder
        run: ls -la public
      
      - name: Upload public folder as Package
        uses: actions/upload-artifact@v3
        with:
          name: public-package
          path: public

  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download the public folder to deploy Job
        uses: actions/download-artifact@v3
        with:
          name: public-package
          path: public

      - name: Copy the Public Folder to Ubuntu
        uses: marcodallasanta/ssh-scp-deploy@v1.2.0
        with:
           local: 'public/*'                                                  # Local file path - REQUIRED false - DEFAULT ./
           remote: '~/public/'                                                 # Remote file path - REQUIRED false - DEFAULT ~/
           host: ${{secrets.REMOTE_HOST}}                                      # Remote server address - REQUIRED true
          #  port: ${{secrets.PORT}}                                      # Remote server port - REQUIRED false - DEFAULT 22
           user: ${{secrets.REMOTE_USER}}                                      # Remote server user - REQUIRED true
          #  password: ${{secrets.PASSWORD}}                              # User password - REQUIRED at least one of "password" or "key" 
           key: ${{secrets.SERVER_SSH_KEY}}                                      # Remote server private key - REQUIRED at least one of "password" or "key" 
          #  ARGS: "-rltgoDzvO"
          #  SOURCE: "myapp"
          #  pre_upload: echo "remove the files"  # Command to run via ssh before scp upload - REQUIRED false
          #  post_upload: sudo mv myapp/* /var/www/html/ # Command to run via ssh after scp upload - REQUIRED false
           ssh_options: -o StrictHostKeyChecking=no                     # A set of ssh_option separated by -o - REQUIRED false - DEFAULT -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
          #  scp_options: -v  
           pre_upload: sudo rm -rf /var/www/html/
           post_upload: sudo mv ~/public/* /var/www/html/
